apiVersion: v1
kind: Service
metadata:
  name: shopping-cart
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http2
  selector:
    app: shopping-cart
  type: LoadBalancer

---

apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "shopping-cart"
spec:
  # If changing this, ensure REQUIRED_CONTACT_POINT_NR is more than half this number, to ensure only one cluster
  # will ever bootstrap when starting from scratch.
  replicas: 3
  selector:
    matchLabels:
      app: "shopping-cart"
  template:
    metadata:
      labels:
        app: "shopping-cart"
      annotations:
        traffic.sidecar.istio.io/excludeInboundPorts: "2552,8558"
        traffic.sidecar.istio.io/excludeOutboundPorts: "2552,8558"
    spec:
      containers:
      - name: "shopping-cart"
        image: "gcr.io/stateserv/akka-grpc-ddata-shopping-cart:latest"

        ports:
        - containerPort: 8080
          name: "http"

        env:
        - name: "APP_LABEL"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.labels['app']"
        - name: "REQUIRED_CONTACT_POINT_NR"
          value: "2"
        - name: "JAVA_OPTS"
          value: "-Xms128m -Xmx128m -Dconfig.resource=prod-application.conf"

        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 0.25
            memory: 256Mi

        readinessProbe:
          httpGet:
            path: "/ready"
            port: 8558
          periodSeconds: 10
          failureThreshold: 10
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: "/alive"
            port: 8558
          periodSeconds: 10
          failureThreshold: 10
          initialDelaySeconds: 20

---

# RBAC configuration for kubernetes API discovery mechanism
kind: "Role"
apiVersion: "rbac.authorization.k8s.io/v1"
metadata:
  name: "pod-reader"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---

kind: "RoleBinding"
apiVersion: "rbac.authorization.k8s.io/v1"
metadata:
  name: "read-pods"
subjects:
- kind: "User"
  name: "system:serviceaccount:default:default"
roleRef:
  kind: "Role"
  name: "pod-reader"
  apiGroup: "rbac.authorization.k8s.io"
